# Generated by Django 5.2.1 on 2026-04-24 00:00

import django.utils.timezone
import envios.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("rutas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("nro_doc", models.CharField(max_length=20, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("activo", models.BooleanField(default=True)),
                ("rutas_asignadas", models.ManyToManyField(blank=True, related_name="empleados", to="rutas.ruta")),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="Encomienda",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda])),
                ("descripcion", models.CharField(max_length=255)),
                ("peso_kg", models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_kg])),
                ("costo_envio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado", models.CharField(choices=[("PE", "Pendiente"), ("TR", "En transito"), ("EN", "Entregado"), ("DV", "Devuelto"), ("CA", "Cancelado")], default="PE", max_length=2)),
                ("fecha_registro", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("fecha_entrega_estimada", models.DateField(blank=True, null=True, validators=[envios.validators.validar_fecha_no_pasada])),
                ("fecha_entrega_real", models.DateField(blank=True, null=True)),
                ("destinatario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="encomiendas_recibidas", to="clientes.cliente")),
                ("empleado_registro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="encomiendas_registradas", to="envios.empleado")),
                ("remitente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="encomiendas_enviadas", to="clientes.cliente")),
                ("ruta", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="encomiendas", to="rutas.ruta")),
            ],
            options={
                "verbose_name": "Encomienda",
                "verbose_name_plural": "Encomiendas",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("estado_anterior", models.CharField(choices=[("PE", "Pendiente"), ("TR", "En transito"), ("EN", "Entregado"), ("DV", "Devuelto"), ("CA", "Cancelado")], max_length=2)),
                ("estado_nuevo", models.CharField(choices=[("PE", "Pendiente"), ("TR", "En transito"), ("EN", "Entregado"), ("DV", "Devuelto"), ("CA", "Cancelado")], max_length=2)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("observacion", models.CharField(blank=True, max_length=255)),
                ("empleado", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="historiales_creados", to="envios.empleado")),
                ("encomienda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historial_estados", to="envios.encomienda")),
            ],
            options={
                "verbose_name": "Historial de estado",
                "verbose_name_plural": "Historiales de estado",
                "ordering": ["-fecha"],
            },
        ),
    ]
