# Generated by Django 5.2.1 on 2026-04-24 00:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_estado_alter_cliente_apellidos_and_more'),
        ('envios', '0002_rebuild_legacy_schema'),
        ('rutas', '0002_alter_ruta_options_ruta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellidos'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={'ordering': ['-fecha_cambio']},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nro_doc',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='fecha_entrega_estimada',
        ),
        migrations.RemoveField(
            model_name='historialestado',
            name='fecha',
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega_est',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='volumen_cm3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='fecha_cambio',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rutas_asignadas',
            field=models.ManyToManyField(blank=True, related_name='empleados_asignados', to='rutas.ruta'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_destinatario', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En transito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01, message='El peso minimo es 0.01 kg')]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_remitente', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='envios.empleado'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='encomienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En transito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En transito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
