# Generated by Django 5.2.1 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ruta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("origen", models.CharField(max_length=120)),
                ("destino", models.CharField(max_length=120)),
                ("distancia_km", models.DecimalField(decimal_places=2, max_digits=8)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ruta",
                "verbose_name_plural": "Rutas",
                "ordering": ["codigo"],
            },
        ),
    ]
