# Generated by Django 5.2.1 on 2026-04-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=120)),
                ('destino', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
