# Generated by Django 5.2.1 on 2026-04-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['origen', 'destino'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AddField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='dias_entrega',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ruta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1),
        ),
        migrations.AddField(
            model_name='ruta',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(max_length=100),
        ),
    ]
