# Generated by Django 5.2.1 on 2026-04-24 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("tipo_doc", models.CharField(choices=[("DNI", "DNI"), ("CE", "Carnet de Extranjeria"), ("PAS", "Pasaporte")], default="DNI", max_length=3)),
                ("nro_doc", models.CharField(max_length=20, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
