# Generated by Django 5.2.1 on 2026-04-24 00:45

import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nro_doc',
            field=models.CharField(max_length=15, unique=True, validators=[envios.validators.validar_nro_doc_dni]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_doc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('PAS', 'Pasaporte')], default='DNI', max_length=3),
        ),
    ]
